version: '3.8'

services:
  aplicacao:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aplicacao
    ports:
      - "8081:80"
    volumes:
      - ./application:/var/www/html
    networks:
      - minha-rede

  teste:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teste
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/homologacao  
      - /var/www/html/teste 
    networks:
      - minha-rede

  homologacao:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homologacao
    ports:
      - "8083:80"
    volumes:
      - ./homologacao:/var/www/html
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
