version: '3.8'

services:
  aplicacao:
    image: php:8.1-apache
    container_name: aplicacao
    ports:
      - "8081:80"
    volumes:
      - ./application:/var/www/html
    networks:
      - minha-rede

  teste:
    image: php:8.1-apache
    container_name: teste
    ports:
      - "8082:80"
    volumes:
      - ./teste:/var/www/html
    networks:
      - minha-rede

  homologacao:
    image: php:8.1-apache
    container_name: homologacao
    ports:
      - "8083:80"
    volumes:
      - ./homologacao:/var/www/html
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
